'use client';

import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import Cookies from 'js-cookie';
import { Building2, Check, Loader2 } from 'lucide-react';
import { toast } from 'sonner';
import { authApi } from '../lib/api';

const currencies = ['KES','USD','EUR','GBP','TZS','UGX','RWF','NGN','ZAR','INR','CNY'];
const industries = ['Retail','Wholesale','Restaurant','Pharmacy','Electronics','Grocery','Other'];
const months = ['January','February','March','April','May','June','July','August','September','October','November','December'];

const initial = {
  business: { name: '', startDate: '', currency: 'KES', logoUrl: '', website: '', contactNumber: '', alternateContactNumber: '', country: 'Kenya', state: '', city: '', zipCode: '', landmark: '', timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'Africa/Nairobi', locale: 'en-KE' },
  settings: { businessType: 'Retail', businessTypeOther: '', defaultTaxRate: 0, taxNumber: '', sellingPriceTaxType: 'inclusive', stockAccountingMethod: 'weighted_average', defaultBusinessLocation: 'Main Branch', defaultLowStockThreshold: 5, featurePosOffline: false, featureMultiCurrencySales: false, featureBarcodeScanning: true, featureServiceRepair: false, financialYearStartMonth: 1 },
  owner: { prefix: '', firstName: '', lastName: '', username: '', email: '', password: '', confirmPassword: '' },
};

export default function RegisterBusinessPage() {
  const router = useRouter();
  const [step, setStep] = useState(1);
  const [form, setForm] = useState(initial);
  const [loading, setLoading] = useState(false);
  const labels = ['Business', 'Settings', 'Owner'];
  const progress = useMemo(() => `${Math.round((step / 3) * 100)}%`, [step]);

  function patch(section: keyof typeof initial, key: string, value: any) { setForm((f) => ({ ...f, [section]: { ...(f as any)[section], [key]: value } })); }
  function validate(current = step) {
    if (current === 1) { const b = form.business; if (['name','currency','country','state','city','zipCode','landmark','timezone'].some((k) => !(b as any)[k])) return toast.error('Please complete all required business fields.'), false; }
    if (current === 2) { if (form.settings.businessType === 'Other' && !form.settings.businessTypeOther.trim()) return toast.error('Describe the business type.'), false; if (!form.settings.defaultBusinessLocation.trim()) return toast.error('Default business location is required.'), false; if (Number(form.settings.defaultTaxRate) < 0 || Number(form.settings.defaultTaxRate) > 100) return toast.error('Default tax must be between 0 and 100%.'), false; if (Number(form.settings.defaultLowStockThreshold) < 0) return toast.error('Low stock threshold cannot be negative.'), false; }
    if (current === 3) { if (!form.owner.firstName || !form.owner.username || !form.owner.email || !form.owner.password) return toast.error('Please complete the owner account fields.'), false; if (form.owner.password.length < 8) return toast.error('Password must be at least 8 characters.'), false; if (form.owner.password !== form.owner.confirmPassword) return toast.error('Passwords do not match.'), false; }
    return true;
  }
  function next() { if (validate(step)) setStep((s) => Math.min(3, s + 1)); }
  function back() { setStep((s) => Math.max(1, s - 1)); }
  async function submit(e: React.FormEvent) { e.preventDefault(); if (!validate(3)) return; setLoading(true); try { const { data } = await authApi.onboardBusiness(form); Cookies.set('token', data.token, { expires: 7 }); toast.success('Business workspace created. Welcome in.'); router.push('/'); } catch (err: any) { toast.error(err.response?.data?.message || 'Could not create business workspace'); } finally { setLoading(false); } }

  return <div className="min-h-screen bg-slate-50 px-4 py-8"><div className="mx-auto max-w-5xl">
    <div className="mb-8 flex items-center justify-between"><div className="flex items-center gap-3"><div className="rounded-2xl bg-emerald-600 p-3 text-white"><Building2 /></div><div><h1 className="text-2xl font-bold text-slate-900">Register your business</h1><p className="text-sm text-slate-500">Create an isolated tenant workspace with its own currency, timezone, stock rules, and owner account.</p></div></div><button onClick={() => router.push('/login')} className="rounded-lg border px-4 py-2 text-sm">Back to login</button></div>
    <div className="mb-6 rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-3 flex justify-between text-sm font-medium text-slate-600">{labels.map((label, i) => <span key={label} className={step >= i + 1 ? 'text-emerald-700' : ''}>{i + 1}. {label}</span>)}</div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-600 transition-all" style={{ width: progress }} /></div></div>
    <form onSubmit={submit} className="rounded-2xl border bg-white p-6 shadow-sm">
      {step === 1 && <div className="grid gap-4 md:grid-cols-3"><Input label="Business Name *" value={form.business.name} onChange={(v) => patch('business','name',v)} /><Input label="Start Date" type="date" value={form.business.startDate} onChange={(v) => patch('business','startDate',v)} /><Select label="Currency *" value={form.business.currency} onChange={(v) => patch('business','currency',v)} options={currencies} /><Input label="Upload Logo" type="file" onChange={async (_v, file) => file && patch('business','logoUrl', await fileToDataUrl(file))} /><Input label="Website" value={form.business.website} onChange={(v) => patch('business','website',v)} /><Input label="Business contact number" value={form.business.contactNumber} onChange={(v) => patch('business','contactNumber',v)} /><Input label="Alternate contact number" value={form.business.alternateContactNumber} onChange={(v) => patch('business','alternateContactNumber',v)} /><Input label="Country *" value={form.business.country} onChange={(v) => patch('business','country',v)} /><Input label="State *" value={form.business.state} onChange={(v) => patch('business','state',v)} /><Input label="City *" value={form.business.city} onChange={(v) => patch('business','city',v)} /><Input label="Zip Code *" value={form.business.zipCode} onChange={(v) => patch('business','zipCode',v)} /><Input label="Landmark *" value={form.business.landmark} onChange={(v) => patch('business','landmark',v)} /><Input label="Time zone *" value={form.business.timezone} onChange={(v) => patch('business','timezone',v)} /></div>}
      {step === 2 && <div className="grid gap-4 md:grid-cols-3"><Select label="Business Type / Industry" value={form.settings.businessType} onChange={(v) => patch('settings','businessType',v)} options={industries} />{form.settings.businessType === 'Other' && <Input label="Other business type *" value={form.settings.businessTypeOther} onChange={(v) => patch('settings','businessTypeOther',v)} />}<Input label="Default Tax Rate %" type="number" value={form.settings.defaultTaxRate} onChange={(v) => patch('settings','defaultTaxRate',Number(v))} /><Input label="Tax Number / PIN" value={form.settings.taxNumber} onChange={(v) => patch('settings','taxNumber',v)} /><Select label="Selling Price Tax Type" value={form.settings.sellingPriceTaxType} onChange={(v) => patch('settings','sellingPriceTaxType',v)} options={[[ 'inclusive','Inclusive' ],[ 'exclusive','Exclusive' ]]} /><Select label="Stock Accounting Method" value={form.settings.stockAccountingMethod} onChange={(v) => patch('settings','stockAccountingMethod',v)} options={[[ 'weighted_average','Weighted Average' ],[ 'fifo','FIFO' ],[ 'lifo','LIFO' ]]} /><Input label="Default Business Location *" value={form.settings.defaultBusinessLocation} onChange={(v) => patch('settings','defaultBusinessLocation',v)} /><Input label="Low Stock Alert threshold" type="number" value={form.settings.defaultLowStockThreshold} onChange={(v) => patch('settings','defaultLowStockThreshold',Number(v))} /><Select label="Financial Year Start Month" value={String(form.settings.financialYearStartMonth)} onChange={(v) => patch('settings','financialYearStartMonth',Number(v))} options={months.map((m,i)=>[String(i+1),m])} /><Toggle label="POS offline mode" checked={form.settings.featurePosOffline} onChange={(v) => patch('settings','featurePosOffline',v)} /><Toggle label="Multi-currency sales" checked={form.settings.featureMultiCurrencySales} onChange={(v) => patch('settings','featureMultiCurrencySales',v)} /><Toggle label="Barcode scanning" checked={form.settings.featureBarcodeScanning} onChange={(v) => patch('settings','featureBarcodeScanning',v)} /><Toggle label="Service/repair mode" checked={form.settings.featureServiceRepair} onChange={(v) => patch('settings','featureServiceRepair',v)} /></div>}
      {step === 3 && <div className="grid gap-4 md:grid-cols-2"><Input label="Prefix" value={form.owner.prefix} onChange={(v) => patch('owner','prefix',v)} /><Input label="First Name *" value={form.owner.firstName} onChange={(v) => patch('owner','firstName',v)} /><Input label="Last Name" value={form.owner.lastName} onChange={(v) => patch('owner','lastName',v)} /><Input label="Username *" value={form.owner.username} onChange={(v) => patch('owner','username',v)} /><Input label="Email *" type="email" value={form.owner.email} onChange={(v) => patch('owner','email',v)} /><Input label="Password *" type="password" value={form.owner.password} onChange={(v) => patch('owner','password',v)} /><Input label="Confirm Password *" type="password" value={form.owner.confirmPassword} onChange={(v) => patch('owner','confirmPassword',v)} /><div className="rounded-xl border border-emerald-100 bg-emerald-50 p-4 text-sm text-emerald-900"><Check className="mb-2 h-5 w-5" />This owner becomes the first full admin for the new business workspace.</div></div>}
      <div className="mt-8 flex justify-between border-t pt-5"><button type="button" onClick={back} disabled={step === 1 || loading} className="rounded-lg border px-5 py-2 text-sm disabled:opacity-40">Back</button>{step < 3 ? <button type="button" onClick={next} className="rounded-lg bg-emerald-600 px-5 py-2 text-sm font-medium text-white">Next</button> : <button type="submit" disabled={loading} className="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-5 py-2 text-sm font-medium text-white disabled:opacity-60">{loading && <Loader2 className="h-4 w-4 animate-spin" />} Create Business</button>}</div>
    </form>
  </div></div>;
}
function fileToDataUrl(file: File) { return new Promise<string>((resolve, reject) => { const r = new FileReader(); r.onload = () => resolve(String(r.result || '')); r.onerror = reject; r.readAsDataURL(file); }); }
function Input({ label, value, onChange, type = 'text' }: { label: string; value?: any; type?: string; onChange: (value: any, file?: File) => void }) { return <label className="block text-sm font-medium text-slate-700">{label}<input type={type} value={type === 'file' ? undefined : value ?? ''} onChange={(e) => onChange(type === 'file' ? e.target.value : e.target.value, e.target.files?.[0])} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-emerald-500 focus:outline-none focus:ring-2 focus:ring-emerald-100" /></label>; }
function Select({ label, value, options, onChange }: { label: string; value: string; options: any[]; onChange: (value: string) => void }) { return <label className="block text-sm font-medium text-slate-700">{label}<select value={value} onChange={(e)=>onChange(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-emerald-500 focus:outline-none focus:ring-2 focus:ring-emerald-100">{options.map((o:any)=>Array.isArray(o)?<option key={o[0]} value={o[0]}>{o[1]}</option>:<option key={o} value={o}>{o}</option>)}</select></label>; }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center gap-3 rounded-xl border p-3 text-sm font-medium text-slate-700"><input type="checkbox" checked={checked} onChange={(e)=>onChange(e.target.checked)} className="h-4 w-4 rounded border-slate-300 text-emerald-600" />{label}</label>; }
